<?php

declare(strict_types=1);

namespace AlbertoArena\NetsonsDeploy;

use AlbertoArena\NetsonsDeploy\Commands\CheckCommand;
use AlbertoArena\NetsonsDeploy\Commands\EnvCommand;
use AlbertoArena\NetsonsDeploy\Commands\InstallCommand;
use Illuminate\Support\ServiceProvider;

class NetsonsDeployServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        $this->mergeConfigFrom(
            __DIR__.'/../config/netsons-deploy.php',
            'netsons-deploy'
        );
    }

    public function boot(): void
    {
        $this->registerPublishing();

        if ($this->app->runningInConsole()) {
            $this->commands([
                InstallCommand::class,
                CheckCommand::class,
                EnvCommand::class,
            ]);
        }
    }

    protected function registerPublishing(): void
    {
        if (! $this->app->runningInConsole()) {
            return;
        }

        // The workflow is generated by netsons:install (placeholders substituted),
        // and the .htaccess rules by HtaccessGenerator — neither is publishable.
        $this->publishes([
            __DIR__.'/../config/netsons-deploy.php' => config_path('netsons-deploy.php'),
        ], 'netsons-deploy-config');
    }
}
